export const START_CREATE_APPOINTMENT = "START_CREATE_APPOINTMENT";
export const SUCCESS_CREATE_APPOINTMENT = "SUCCESS_CREATE_APPOINTMENT";
export const ERROR_CREATE_APPOINTMENT = "ERROR_CREATE_APPOINTMENT";

export const START_GET_BOOKED_SLOTS = "START_GET_BOOKED_SLOTS";
export const SUCCESS_GET_BOOKED_SLOTS = "SUCCESS_GET_BOOKED_SLOTS";
export const ERROR_GET_BOOKED_SLOTS = "ERROR_GET_BOOKED_SLOTS";
