export const START_USER_LOGIN = "START_USER_LOGIN";
export const SUCCESS_USER_LOGIN = "SUCCESS_USER_LOGIN";
export const ERROR_USER_LOGIN = "ERROR_USER_LOGIN";

export const START_USER_REGISTER = "START_USER_REGISTER";
export const SUCCESS_USER_REGISTER = "SUCCESS_USER_REGISTER";
export const ERROR_USER_REGISTER = "ERROR_USER_REGISTER";

export const START_GET_USER_DETAILS = "START_GET_USER_DETAILS";
export const SUCCESS_GET_USER_DETAILS = "SUCCESS_GET_USER_DETAILS";
export const ERROR_GET_USER_DETAILS = "ERROR_GET_USER_DETAILS";
